Backend/MetalCyclse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("app.urls")),
    path("administrador/", include("administrador.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
    path('registro/', views.registro_cliente, name='registro_cliente'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('MotoAdventure', views.MotoAdventure, name='MotoAdventure'),
    path('MotoCompeticion', views.MotoCompeticion, name='MotoCompeticion'),
    path('MotoDeportiva', views.MotoDeportiva, name='MotoDeportiva'),
    path('MotoScooter', views.MotoScooter, name='MotoScooter'),
    path('MotoTouring', views.MotoTouring, name='MotoTouring'),
    path('MotoUrbana', views.MotoUrbana, name='MotoUrbana'),
    path('tienda/', views.tienda, name='tienda'),  # Nueva URL para la tienda
    path('carrito/', views.carrito, name='carrito'),  # Nueva URL para el carrito
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/administrador/urls.py
from django.urls import path, include
from . import views
from .views import CustomLoginView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

app_name = "administrador"

urlpatterns = [
    path('loginAdmin/', CustomLoginView.as_view(), name='loginAdmin'),
    path('menu/', views.menu, name='menu'),
    path('productos/', views.lista_productos, name='lista_productos'),
    path('productos/agregar/', views.agregar_producto, name='agregar_producto'),
    path('productos/modificar/<int:id>/', views.modificar_producto, name='modificar_producto'),
    path('productos/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('accounts/', include('django.contrib.auth.urls')),
]

Backend/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('registro/', views.registro_cliente, name='registro_cliente'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('MotoAdventure/', views.MotoAdventure, name='MotoAdventure'),
    path('MotoCompeticion/', views.MotoCompeticion, name='MotoCompeticion'),
    path('MotoDeportiva/', views.MotoDeportiva, name='MotoDeportiva'),
    path('MotoScooter/', views.MotoScooter, name='MotoScooter'),
    path('MotoTouring/', views.MotoTouring, name='MotoTouring'),
    path('MotoUrbana/', views.MotoUrbana, name='MotoUrbana'),
    path('tienda/', views.tienda, name='tienda'),  # Ruta para la tienda
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/', views.carrito, name='carrito'),
]

Backend/administrador/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class TipoMoto(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.nombre)

class ModeloMoto(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    tipo = models.ForeignKey(TipoMoto, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.nombre} ({self.tipo})"

class Producto(models.Model):
    modelo = models.ForeignKey(ModeloMoto, on_delete=models.CASCADE)
    descripcion = models.TextField()
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to="productos/", null=True, blank=True)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.modelo} - {self.descripcion}"

class AdminManager(BaseUserManager):
    def create_user(self, username, email=None, password=None):
        if not username:
            raise ValueError('El usuario debe tener un nombre de usuario')
        user = self.model(
            username=username,
            email=self.normalize_email(email) if email else None,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None):
        user = self.create_user(
            username=username,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Admin(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='admin_set',
        blank=True,
        help_text=('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
        verbose_name=('groups')
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='admin_permissions_set',
        blank=True,
        help_text=('Specific permissions for this user.'),
        verbose_name=('user permissions')
    )

    objects = AdminManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    @property
    def is_staff(self):
        return self.is_admin

Backend/administrador/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = "__all__"

    def clean_precio(self):
        precio = self.cleaned_data["precio"]
        return round(precio, 2)

Backend/administrador/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.views import LoginView
from .models import Producto
from .forms import ProductoForm

@login_required(login_url="/administrador/accounts/loginAdmin/")
def menu(request):
    context = {}
    return render(request, "administrador/menu.html", context)


@login_required(login_url="/administrador/accounts/loginAdmin/")
def login_admin(request):
    context = {}
    return render(request, "administrador/loginAdmin.html", context)



class CustomLoginView(LoginView):
    template_name = "registration/loginAdmin.html"


@login_required
@permission_required("administrador.view_producto", raise_exception=True)
def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, "administrador/productoLista.html", {"productos": productos})

@login_required
@permission_required("administrador.add_producto")
def agregar_producto(request):
    data = {"form": ProductoForm()}
    if request.method == "POST":
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "guardado correctamente"
            return redirect("administrador:lista_productos")
        else:
            data["form"] = formulario
    return render(request, "administrador/agregarProducto.html", data)

@login_required
@permission_required("administrador.change_producto", raise_exception=True)
def modificar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == "POST":
        formulario = ProductoForm(request.POST, request.FILES, instance=producto)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto modificado correctamente.")
            return redirect("administrador:lista_productos")
    else:
        formulario = ProductoForm(instance=producto)
    return render(
        request,
        "administrador/modificarProducto.html",
        {"form": formulario, "producto": producto},
    )

@login_required
@permission_required("administrador.delete_producto", raise_exception=True)
def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.delete()
    return redirect("administrador:lista_productos")

Backend/administrador/templates/administrador/agregarProducto.html
{% extends 'administrador/baseProducto.html' %}
{% block contenido %}

{% load crispy_forms_tags %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6" style="display:flex; justify-content:center; align-items:center;">

            <form action="" method="post" enctype="multipart/form-data" class="text-center" style="width: 100%;">
                <h1>Nuevo producto</h1>

                {% csrf_token %}
                {{ form | crispy }}

                <div class="d-flex justify-content-around mt-3">
                    <input type="reset" value="Cancelar" class="btn btn-secondary">
                    <input type="submit" value="Guardar" class="btn btn-primary">
                </div>
            </form>
            {{mensaje}}
        </div>
    </div>
</div>

{% endblock %}

Backend/administrador/templates/administrador/baseProducto.html
<!DOCTYPE html>
<html lang="en">


<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/administrador.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body class="fondo">

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand fs-2" href="#">Administrador</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Reporte
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'administrador:lista_productos' %}">Lista
                                    Productos</a></li>
                            <li><a class="dropdown-item" href="#">Reporte Motos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Mantenedor</a>
                    </li>
                    {% block user_info %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hola! {{ user.username|striptags }}</a>
                    </li>
                    <li class="nav-item">
                        <form method="POST" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{% url 'administrador:menu' %}">
                            <button type="submit" class="btn btn-link nav-link">Cerrar Sesión</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                    {% endblock user_info %}
                </ul>
            </div>
        </div>
    </nav>



    <div>

        {% block contenido%}

        {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

Backend/administrador/templates/administrador/menu.html
{% extends 'administrador/baseProducto.html' %}

{% block content %}



{% endblock %}

Backend/administrador/templates/administrador/modificarProducto.html
{% extends 'administrador/baseProducto.html' %}
{% block contenido %}

{% load crispy_forms_tags %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6" style="display:flex; justify-content:center; align-items:center;">

            <form action="" method="post" enctype="multipart/form-data" class="text-center" style="width: 100%;">
                <h1>Modificar producto</h1>

                {% csrf_token %}
                {{ form | crispy }}

                <div class="d-flex justify-content-around mt-3">
                    <input type="reset" value="Cancelar" class="btn btn-secondary">
                    <input type="submit" value="Guardar" class="btn btn-primary">
                </div>
            </form>
            {{mensaje}}
        </div>
    </div>
</div>

{% endblock %}

Backend/administrador/templates/administrador/productoLista.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <title>Lista de Productos</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="{% static 'app/js/confirmar.js' %}"></script>
    <link rel="stylesheet" href="{% static 'app/css/administrador.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="fondo">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand fs-2" href="#">Administrador</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#Contacto" data-bs-toggle="modal">Mantenedor</a>
                    </li>

                    {% if user.is_authenticated %} <li class="nav-item">
                        <a class="nav-link" href="{% url 'administrador:menu' %}">Menu</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <form method="POST" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{% url 'administrador:menu' %}">
                            <button type="submit" class="btn btn-link nav-link">Cerrar Sesión</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <h1>Listado de Productos</h1>
        </div>
        <br>

        <div class="row mb-3">
            <table class="table table-bordered" id="productos">
                {% load humanize %}
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Modelo</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Imagen</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.modelo }}</td>
                    <td>{{ producto.modelo.tipo }}</td>
                    <td>${{ producto.precio | intcomma }}</td>
                    <td>{{ producto.stock }}</td>
                    <td>
                        {% if producto.imagen %}
                        <img src="{{ producto.imagen.url }}" alt="Imagen del producto" style="max-width: 100px;">
                        {% else %}
                        <span>Sin imagen</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'administrador:modificar_producto' producto.id %}"
                            class="btn btn-warning btn-sm">
                            <i class="fas fa-edit"></i> Actualizar
                        </a>
                        <a href="{% url 'administrador:eliminar_producto' producto.id %}"
                            onclick="confirmarEliminacion({{ producto.id }}); return false;"
                            class="btn btn-danger btn-sm">
                            <i class="fas fa-trash-alt"></i> Eliminar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <br>
        <div class="row d-grid gap-2 col-6 mx-auto">
            <a href="{% url 'administrador:agregar_producto' %}" class="btn btn-success">
                <i class="fas fa-plus"></i> Agregar Nuevo Producto
            </a>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <script>
        function confirmarEliminacion(productoId) {
            if (confirm("¿Estás seguro de que deseas eliminar este producto?")) {

                window.location.href = "{% url 'administrador:eliminar_producto' 0 %}".replace('0', productoId);
            }
        }
    </script>
</body>

</html>